CREATE TABLE `ta_golden_cross_detail`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`identifier` varchar(64),
	`golden_cross_id` bigint (20) NOT NULL,
	`flash_time` bigint (20),
	`flash_price` decimal (10,4),
	`volume`bigint (20),
	`vwap`decimal(10,4),
	`checked` bigint (20),
	`success`bit(1) DEFAULT 0,
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`golden_cross_id`) REFERENCES `ta_golden_cross` (`id`),
	UNIQUE KEY `UK_golden_cross_id_flash_time` (`golden_cross_id`,`flash_time`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
