
	
CREATE TABLE `sa_trade`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`identifier` varchar(64),
	`name` varchar(64),
	`order_type` varchar(64),
	`order_side` varchar(64),
	`stock` varchar(64),
	`currency_type` varchar(64),
	`currency_amount` decimal(10,4),
	`profit_limit_type` varchar(64),
	`profit_limit_amount` decimal(10,4),
	`trailing_stop_type` varchar(64),
	`trailing_stop_amount` decimal(10,4),
	`buy_condition` varchar(128) NOT NULL,
	`sell_condition` varchar(128) NOT NULL,
	`frequency` varchar(64),
	`frequency_executed` bigint(20),
	`run_status` varchar(48) NOT NULL,
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
